import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/util/Provider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/faviconLiveload.png" />
      </head>
      <body className={inter.className}>
        <Toaster position="top-right" />
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
